[tool.poetry]
name = "gus"
version = "0.1.4"
description = "Green Urban Scenarios - A digital twin representation, simulation of urban forests and their impact analysis."
authors = ["Bulent Ozel <bulent@lucidminds.ai>"] 
maintainers = [
    "Oguzhan Yayla <oguzhan@lucidminds.ai>", 
    "Marko Petrovic <marko@lucidminds.ai>", 
    "Axel Nilsson <axel@darkmatterlabs.org>"
]
license = "Apache License 2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    'Environment :: Console',
    'Operating System :: OS Independent',
    'Intended Audience :: Developers',
    'License :: Other/Proprietary License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Utilities'
]
packages = [
    {include = "gus", from = "src" }
]


[tool.poetry.dependencies]
python = "^3.8.0"
appdirs = "^1.4.4"
appnope = "^0.1.2"
argon2-cffi = "^21.1.0"
arrow = "^1.2.0"
attrs = "^21.2.0"
backcall = "^0.2.0"
binaryornot = "^0.4.4"
bleach = "^4.1.0"
cachetools = "^4.2.4"
certifi = "^2021.5.30"
cffi = "^1.14.6"
chardet = "^4.0.0"
charset-normalizer = "^2.0.5"
click = "^8.0.1"
cookiecutter = "^1.7.3"
cycler = "^0.10.0"
datapoint = "^0.9.8"
debugpy = "^1.5.0"
decorator = "^5.1.0"
defusedxml = "^0.7.1"
entrypoints = "^0.3"
idna = "^3.2"
ipdb = "^0.13.9"
ipykernel = "^6.4.1"
ipython = "^7.27.0"
ipython-genutils = "^0.2.0"
ipywidgets = "^7.6.5"
jedi = "^0.18.0"
jinja2 = "^3.0.2"
jinja2-time = "^0.2.0"
jsonschema = "^4.0.1"
jupyter = "^1.0.0"
jupyter-client = "^7.0.6"
jupyter-console = "^6.4.0"
jupyter-core = "^4.8.1"
jupyterlab-pygments = "^0.1.2"
jupyterlab-widgets = "^1.0.2"
kiwisolver = "^1.3.2"
lxml = "^4.6.3"
mako = "^1.1.5"
markdown = "^3.3.4"
markupsafe = "^2.0.1"
matplotlib = "^3.4.3"
matplotlib-inline = "^0.1.3"
mesa = "^0.8.9"
mistune = "^0.8.4"
nbclient = "^0.5.4"
nbconvert = "^6.2.0"
nbformat = "^5.1.3"
nest-asyncio = "^1.5.1"
networkx = "^2.6.3"
notebook = "^6.4.4"
numpy = "^1.21.2"
oauthlib = "^3.1.1"
packaging = "^21.0"
pandas = "^1.3.3"
pandocfilters = "^1.5.0"
parso = "^0.8.2"
pdoc3 = "^0.10.0"
pexpect = "^4.8.0"
pickleshare = "^0.7.5"
pillow = "^8.3.2"
poyo = "^0.5.0"
prometheus-client = "^0.11.0"
prompt-toolkit = "^3.0.20"
ptyprocess = "^0.7.0"
pyasn1 = "^0.4.8"
pyasn1-modules = "^0.2.8"
pycparser = "^2.20"
pygments = "^2.10.0"
pyparsing = "^2.4.7"
pyrsistent = "^0.18.0"
python-dateutil = "^2.8.2"
python-slugify = "^5.0.2"
pytz = "^2021.1"
pyzmq = "^22.3.0"
qtconsole = "^5.1.1"
qtpy = "^1.11.2"
requests = "^2.26.0"
requests-oauthlib = "^1.3.0"
rsa = "^4.8"
send2trash = "^1.8.0"
six = "^1.16.0"
terminado = "^0.12.1"
testpath = "^0.5.0"
text-unidecode = "^1.3"
toml = "^0.10.2"
tornado = "^6.1"
traitlets = "^5.1.0"
urllib3 = "^1.26.6"
wcwidth = "^0.2.5"
webencodings = "^0.5.1"
widgetsnbextension = "^3.5.1"
xlrd = "^2.0.1"
fuzzywuzzy = "^0.18.0"
python-levenshtein = "^0.12.2"
seaborn = "^0.11.2"
pytest = "^7.1.2"
twine = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
